name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - uses: jdx/mise-action@v4
      - run: wasm-pack test --headless --chrome

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --workspace --no-deps --all-features
        env:
          RUSTDOCFLAGS: -D warnings

  msrv:
    name: MSRV (1.92)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.92"
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - uses: jdx/mise-action@v4
      - run: wasm-pack test --headless --chrome

  #minimal-versions:
  #  name: Minimal versions
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v6
  #    - uses: dtolnay/rust-toolchain@nightly
  #      with:
  #        targets: wasm32-unknown-unknown
  #    - uses: dtolnay/rust-toolchain@stable
  #      with:
  #        targets: wasm32-unknown-unknown
  #    - uses: Swatinem/rust-cache@v2
  #    - run: cargo +nightly update -Z minimal-versions
  #    - run: cargo build --workspace
